### ISSUE TITLE
Compare to Jetpack Compose Multiplatform

### ISSUE THREAD

**Issue by esafak** [1gravity/Kotlin-Bloc#16]
Can you clarify in the README the appropriate use of this framework versus JCM?

**Comment by 1gravity** [comment]
@esafak what is JCM?

**Comment by 1gravity** [comment]
@esafak there's no such thing as Jetpack Compose Multiplatform.

Jetpack Compose is Android only, Compose Multiplatform is view layer only, Kotlin Bloc bridges the gap between the view and the business logic.
